ALTER TABLE profile ADD COLUMN avatarUrl TEXT;
ALTER TABLE profile ADD COLUMN statusLine TEXT;
ALTER TABLE profile ADD COLUMN birthDay INTEGER;
ALTER TABLE profile ADD COLUMN birthMonth INTEGER;
ALTER TABLE profile ADD COLUMN birthYear INTEGER;
ALTER TABLE profile ADD COLUMN hideBirthYear BOOL NOT NULL DEFAULT false;
ALTER TABLE profile ADD COLUMN city TEXT;
ALTER TABLE profile ADD COLUMN favouriteYaku TEXT;
ALTER TABLE profile ADD COLUMN favouriteTile TEXT;
ALTER TABLE profile ADD COLUMN discord TEXT;
ALTER TABLE profile ADD COLUMN majsoulAccount TEXT;
ALTER TABLE profile ADD COLUMN tenhouAccount TEXT;

ALTER TABLE club ADD COLUMN logoUrl TEXT;
